config/routes.rb
Rails.application.routes.draw do
  get 'feedback_question/index'

  get 'feedback/index'

  get 'suggestion/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'reports#index'
  resources :reports do
    collection do
      get :search_by_dates
      get :generate_sheet
      get :employees_list
      get :change_employee_position
      get :download_sheet
    end
  end
  resources :suggestion do

  end
  resources :feedback do

  end
  resources :feedback_question do

  end
end

app/models/feedback_question.rb
# == Schema Information
#
# Table name: feedback_questions
#
#  id            :integer          not null, primary key
#  creater       :string(255)
#  question_type :string(255)
#  description   :text(65535)
#  has_option    :boolean
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class FeedbackQuestion < ApplicationRecord
  has_many :question_options
end

app/controllers/feedback_question_controller.rb
class FeedbackQuestionController < ApplicationController
  def index
    @feedback  = Feedback.new
    @feedback_questions = FeedbackQuestion.all
  end
  def edit
    byebug
  end
  def create
    byebug
  end

end

app/helpers/feedback_question_helper.rb
module FeedbackQuestionHelper
end

app/views/feedback_question/index.html.erb
<div>
  <h2 style="text-align: center;">Feedback Page</h2>
  <br>

  <%#= form_for :feedback_question, url: feedback_question_index_path do |f| %>
    <% @feedback_questions.each_with_index do |f,index| %>
    <%= form_for f, url: edit_feedback_question_path(f),method: "GET", class: "feed_back_form" do |d| %>
    <div class="col-lg-10" style="margin-left: 200px; margin-top: 50px; border: solid 1px">
      <%= f.description %>
      <br>
      <%# f.fields_for :question_options  do |option| %>
      <% f.question_options.each_with_index do |option| %>
        <div><input type="radio" name="optin" > <%= option.option  %></div>
      <% end %>
    </div>
    <% end %>

  <% end %>
  <input type="button" value="Submit" id="send_feedback">
</div>
<script>
  $('#send_feedback').click(function () {
     $('.feed_back_form').submit();
  });
</script>