config/routes.rb
Rails.application.routes.draw do
  get 'feedback_question/index'

  get 'feedback/index'

  get 'suggestion/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'reports#index'
  resources :reports do
    collection do
      get :search_by_dates
      get :generate_sheet
      get :employees_list
      get :change_employee_position
      get :download_sheet
    end
  end
  resources :suggestion do

  end
  resources :feedback do

  end
  resources :feedback_question do

  end
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id              :integer          not null, primary key
#  emp_id          :string(255)
#  time_in_office  :float(24)
#  time_out_office :float(24)
#  source          :string(255)
#  report_date     :date
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  require 'rubygems'
  require 'write_xlsx'
  require 'rubygems'
  require 'zip'
  def index
    if current_user.role == "employee"
      redirect_to suggestion_index_path
    else
      if params[:start_date].present? && params[:end_date].present?
        startDate = params[:start_date].split('/')
        month = startDate[0] rescue ""
        day = startDate[1] rescue ""
        year = startDate[2] rescue ""
        startDate = params[:end_date].split('/')
        month2 = startDate[0] rescue ""
        day2 = startDate[1] rescue ""
        year2 = startDate[2] rescue ""
        @start_Date = (day +"-" + month +"-" + year).to_date
        @end_date = (day2 +"-" + month2 +"-" + year2).to_date
        # @reports = Report.where(report_date: year+"-"+month+"-"+day...year2+"-"+month2+"-"+((day2.to_i) +1).to_s,source: "Network Sheet")
      else
        @start_Date = ('2019-12-02').to_date
        @end_date = ('2019-12-06').to_date
      end
      if params[:search_name].present?
        @employees = EmployeeDatum.where("name LIKE ?", "%#{params[:search_name]}%")
      else
        @employees = EmployeeDatum.all.order("employee_id")
      end
    end
    # @reports = Report.group(report_date,emp_id).order('report_date asc')
    # @reports = Report.order('report_date asc').group_by{|rep| [rep.report_date, rep.emp_id,rep.source]}

  end
  
  def search_by_dates
    if params[:start_date].present? && params[:end_date]
      startDate = params[:start_date].split('/')
      month = startDate[0] rescue ""
      day = startDate[1] rescue ""
      year = startDate[2] rescue ""
      startDate = params[:end_date].split('/')
      month2 = startDate[0] rescue ""
      day2 = startDate[1] rescue ""
      year2 = startDate[2] rescue ""
      @start_Date = (day +"-" + month +"-" + year).to_date
      @end_date = (day2 +"-" + month2 +"-" + year2).to_date
      @employees = EmployeeDatum.all
      # @reports = Report.where(report_date: year+"-"+month+"-"+day...year2+"-"+month2+"-"+((day2.to_i) +1).to_s,source: "Network Sheet")
    end
    render 'index'
  end
  def change_employee_position
    if params[:left] == "true"
      emp = EmployeeDatum.find params[:empid]
      emp.has_left = false
      emp.save
    else
      emp = EmployeeDatum.find params[:empid]
      emp.has_left = true
      emp.save
    end

  end
  def employees_list
    @list = EmployeeDatum.all
  end
  def download_sheet(zip_data,filename)
    send_data(zip_data, :type => 'application/zip', :filename => filename)
    puts "--------------------"
    puts "--------------------"
  end
  def generate_sheet
    # byebug
    @start_Date = ('2019-01-07').to_date
    @end_Date = ('2019-05-14').to_date
    @employees = EmployeeDatum.all.order("employee_id")

    workbook = WriteXLSX.new("public/Reports/Intagleo Report.xlsx")
    (@start_Date..@end_Date).each do |date_report|
      filenam = date_report.to_s
      # workbook = WriteXLSX.new("public/Reports/intagleo report "+ filenam +".xlsx")
      worksheet = workbook.add_worksheet(filenam)
      format = workbook.add_format
      format2 = workbook.add_format
      row = 2
      format.set_bold
      format2.set_color('red')
      worksheet.write(0, 0, "ID",format)
      worksheet.write(0, 1, "Name",format)
      worksheet.write(0, 2, "HR Sheet Time",format)
      worksheet.write(0, 3, "Network Sheet Time",format)
      worksheet.write(0, 4, "HRM Attendance Total Time",format)
      worksheet.write(0, 5, "Report Date",format)
      worksheet.write(0, 6, "Status",format)
      @employees.each do |emp|
        r1 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "HR Sheet")
        r2 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "Network Sheet")
        r3 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "HRM_ATTENDENCE")
        # next unless r1.present? || r2.present? || r3.present?


        worksheet.write(row, 0, emp.employee_id)
        worksheet.write(row, 1, emp.name)
        if r1.present?
          if r1.time_in_office > 0 && r1.time_in_office <= 3
            worksheet.write(row, 2, r1.time_in_office.round(1),format2)
          else
            worksheet.write(row, 2, r1.time_in_office.round(1))
          end

        end
        if r2.present?
          if r2.time_in_office > 0 && r2.time_in_office <= 3
            worksheet.write(row, 3, r2.time_in_office.round(1),format2)
          else
            worksheet.write(row, 3, r2.time_in_office.round(1))
          end

        end
        if r3.present?
          if r3.time_in_office > 0 && r3.time_in_office <= 3
            worksheet.write(row, 4, r3.time_in_office,format2)
          else
            worksheet.write(row, 4, r3.time_in_office)
          end

        end
        worksheet.write(row, 5, date_report)
        diff = nil
        if r1.present? && r1.time_in_office != 0
          if r2.present? && r2.time_in_office - r1.time_in_office <= -2 && r2.time_in_office != 0
            diff = r2.time_in_office - r1.time_in_office
          else
            if r3.present?
              if (r3.time_in_office.round(1) - r1.time_in_office) <= -2 && r3.time_in_office != 0
                diff = r3.time_in_office.round(1) - r1.time_in_office
              end
            end
          end
        else
          if r3.present? && r2.present?
            if (r2.time_in_office.round(1) - r3.time_in_office) <= -3 && r2.time_in_office != 0
              diff = r2.time_in_office.round(1) - r3.time_in_office
            end
          end
        end
        if diff.present?
          worksheet.write(row, 6, diff, format2)
        end
        row = row + 1
      end

    end
    workbook.close

    # reportFile = File.open('public/Reports/Intagleo Report.xlsx')
    # send_data(reportFile, :filename => "Intagleo Report.xlsx")
    folder = "public"
    filename = 'Intagleo_Reports.zip'
    temp_file = Tempfile.new(filename)

    reportFiles = Dir.entries('public/Reports')
    Zip::File.open(temp_file.path, Zip::File::CREATE) do |zip_file|
      reportFiles.each do |d|
        unless d == "." || d == ".."
          zip_file.add(d,"public/Reports/"+d)
        end
      end
    end
    zip_data = File.read(temp_file.path)
    ###### redirect_to download_sheet_reports_path(zip_data,filename)
    send_data(zip_data, :type => 'application/zip', :filename => filename)

    #
    #
    #
    #
    #
    # render :json=>{"status"=>"success"}
   
    # ============old code=============
    # workbook = WriteXLSX.new('intagleo report.xlsx')
    # worksheet = workbook.add_worksheet
    # format = workbook.add_format
    # format2 = workbook.add_format
    # row = 2
    # format.set_bold
    # format2.set_color('red')
    # worksheet.write(0, 0, "ID",format)
    # worksheet.write(0, 1, "Name",format)
    # worksheet.write(0, 2, "Network Sheet Time",format)
    # worksheet.write(0, 3, "HR Sheet Time",format)
    # worksheet.write(0, 4, "HRM Attendance Total Time",format)
    # worksheet.write(0, 5, "Report Date",format)
    # worksheet.write(0, 6, "Status",format)
    # reports = Report.where(source: "Network Sheet")
    # reports.each_with_index do |report,index|
    #   r1 = Report.find_by(emp_id: report.emp_id,report_date: report.report_date, source: "HR Sheet")
    #   r2 = Report.find_by(emp_id: report.emp_id,report_date: report.report_date, source: "HRM_ATTENDENCE")
    #
    #   worksheet.write(row, 0, report.emp_id)
    #   worksheet.write(row, 1, EmployeeDatum.find_by(employee_id: report.emp_id).name)
    #   worksheet.write(row, 2, report.time_in_office.round(1))
    #   if r1.present?
    #     worksheet.write(row, 3, r1.time_in_office.round(1))
    #   end
    #   if r2.present?
    #     worksheet.write(row, 4, r2.time_in_office)
    #   end
    #   worksheet.write(row, 5, report.report_date)
    #   if r1.present?
    #     if report.time_in_office - r1.time_in_office < -2 && report.time_in_office != 0
    #       worksheet.write(row, 6, (report.time_in_office - r1.time_in_office).round(1),format2)
    #     else
    #       if r2.present?
    #         if (report.time_in_office.round(1) - r2.time_in_office) < -3 && report.time_in_office != 0
    #           worksheet.write(row, 6, (report.time_in_office - r2.time_in_office).round(1),format2)
    #         else
    #           if r1.time_in_office - r2.time_in_office <-3 && r1.time_in_office != 0
    #             worksheet.write(row, 6, (r1.time_in_office - r2.time_in_office).round(1),format2)
    #           end
    #         end
    #       end
    #     end
    #   else
    #     if r2.present?
    #       if (report.time_in_office.round(1) - r2.time_in_office) < -3 && report.time_in_office != 0
    #         worksheet.write(row, 6, (report.time_in_office - r2.time_in_office).round(1),format2)
    #       end
    #     end
    #   end
    #   # if r2.present?
    #   #   if (report.time_in_office.round(1) - r2.time_in_office) < -3
    #   #     format2.set_color('red')
    #   #     worksheet.write(row,0, format2)
    #   #   end
    #   # end
    #   row = row + 1
    # end
    # workbook.close
    # redirect_to root_path

  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/employees_list.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Intagleo Report</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item pull-right active">
        <%= link_to('Employees', employees_list_reports_path, class: "nav-link") %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item pull-right">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        </li>
      <% end %>
      <!--      <li class="nav-item">-->
      <!--        <a class="nav-link" href="#">Link</a>-->
      <!--      </li>-->
      <!--      <li class="nav-item">-->
      <!--        <a class="nav-link disabled" href="#">Disabled</a>-->
      <!--      </li>-->
      <!--      <li class="nav-item dropdown">-->
      <!--        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>-->
      <!--        <div class="dropdown-menu" aria-labelledby="dropdown01">-->
      <!--          <a class="dropdown-item" href="#">Action</a>-->
      <!--          <a class="dropdown-item" href="#">Another action</a>-->
      <!--          <a class="dropdown-item" href="#">Something else here</a>-->
      <!--        </div>-->
      <!--      </li>-->
    </ul>

  </div>
</nav>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->



  <div class="container mt-5">
    <!-- Example row of columns -->

      <div class="row mt-4 mb-4">
        <div class="col-md-9" >
          <h2 class="mb-4" >Report</h2>
        </div>
      </div>



    <!--         -->
    <div class="row">
      <div class="col-md-12">

        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">Name</th>
            <th scope="col">Has Left</th>
          </tr>
          </thead>
          <tbody>
          <% @list.each_with_index do |emp,index|  %>
          <tr>
            <td><%= index+1 %></td>
          <td><%= emp.name %></td>
            <td style="text-align: center;">
              <img  src= <%= emp.has_left ? image_url('red_button.jpeg') : image_url('green_button.jpeg') %> height='20' width='20' onclick="has_left_function(<%= emp.id %>)"  style="margin-top: 14px;" id=<%= "has_left_image" + emp.id.to_s %> >
            </td>
          <% end %>
          </tr>
          </tbody>
        </table>
      </div>

    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; <a href="https://www.intagleo.com/" target="_blank">Intagleo.com</a> 2019</p>
</footer>

<script type="text/javascript">
    function has_left_function(e) {
        var element = document.getElementById('has_left_image'+ e.toString()).src;
        var left = element.includes("red");
        $.ajax({
                 url: "/reports/change_employee_position",
                 type: "GET",
                  data: {empid: e,left: left},
                 success: function(data) {
                   }
                 });
        if (left)
        {
            $('#has_left_image'+ e.toString()).attr('src', '/green_button.jpeg'  );
        }
        else
        {

            $('#has_left_image'+ e.toString()).attr('src', '/red_button.jpeg'  );
        }
        return false;
        // alert( );
    }
</script>

app/views/reports/generate_sheet.js.erb
<%send_data(@zip_data, :type => 'application/zip', :filename => @filename)%>

app/views/reports/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Intagleo Report</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item pull-right">
        <%= link_to('Employees', employees_list_reports_path, class: "nav-link") %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item pull-right">
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>  
        </li>
      <% end %>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>-->
<!--        <div class="dropdown-menu" aria-labelledby="dropdown01">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
    </ul>

  </div>
</nav>

<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->



  <div class="container mt-5">
    <!-- Example row of columns -->
    <form accept-charset="UTF-8" action=<%= reports_path %> method="get" autocomplete="off">
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <input type="text" class="form-control datepicker " name="start_date" id="start_date" placeholder="Start date" value = "<%= params[:start_date].present? ? params[:start_date] : '' %>">
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">

            <input type="text" class="form-control datepicker" name="end_date" id="end_date" placeholder="End date", value= "<%= params[:end_date].present? ? params[:end_date] : '' %>">
          </div>
        </div>

        <div class="col-md-3">
          <div class="form-group">
            <input type="text" class="form-control" id="search_name" placeholder="Search by name" name="search_name" value = "<%= params[:search_name].present? ? params[:search_name] : '' %>">
          </div>
        </div>
        <div class="col-md-1">
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="search_button">Submit</button>
          </div>
        </div>
      </div>
      
      <hr>
      <div class="row mt-4 mb-4">
        <div class="col-md-9" >
          <h2 class="mb-4" >Report</h2>
          <span style="color: #666666">1- Too high value in HRM attendance column means resource forgot to log out.</span><br>
          <span style="color: #666666">2- Too high value in HR sheet means resource did not follow standard pattern of HR time sheet.</span><br>
          <span style="color: #666666">3- We have handled night shift resources in our algorithm.</span><br>
          <span style="color: #666666">4- Not all resources are covered because javed is still working on network logs of all employees.</span><br>
          
        </div>
      </div>

      <hr>

      <div class="row mt-4 mb-4">
        

        <div class="col-md-12">
          <div style="float: right"><%= link_to "Generate Report", generate_sheet_reports_path ,:class => "btn btn-primary btn-sm" ,  :id => "generate_report", :onclick => 'return openPopup(this);' %></div>
         <!--  <%= form_tag({:controller => 'reports', :action => 'generate_sheet'},:id => 'filter_form', :remote => true) do %>
              
            <%= submit_tag 'save', :name => 'commit'%><%end%> -->

          <!-- <button id="generate_report_btn"> G R </button> -->
        </div> 
      </div>
    </form>
    <!--         -->
    <div class="row">
      <div class="col-md-12">

        <table class="table table-hover table-bordered">
          <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">HR Sheet Time</th>
            <th scope="col">Network Sheet Time</th>
            <th scope="col">HRM Attendance Total Time</th>
            <th scope="col">Report Date</th>
            <th scope="col">Status</th>
          </tr>
          </thead>
          <tbody>

          <% sr = 0 %>
          <% (@start_Date..@end_date).each do |date_report| %>
            <% @employees.each do |emp| %>
              <% r1 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "HR Sheet") %>
              <% r2 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "Network Sheet") %>
              <% r3 = Report.find_by(emp_id: emp.employee_id,report_date: date_report, source: "HRM_ATTENDENCE") %>
              <%# next unless r1.present? || r2.present? || r3.present? %>
              <tr><% sr = sr + 1 %>
              <td><%= sr %></td>
              <td><%= emp.employee_id %></td>
              <td><%= emp.name %></td>
              <td <% if (r1.present?) && (r1.time_in_office > 0 && r1.time_in_office <= 3)%>style = "background: red;" <% end  %> ><%= r1.time_in_office.round(1) if r1.present? %></td>
              <td <% if (r2.present?) && (r2.time_in_office > 0 && r2.time_in_office <= 3)%>style = "background: red;" <% end  %> ><%= r2.time_in_office.round(1) if r2.present? %></td>
              <td <% if (r3.present?) && (r3.time_in_office > 0 && r3.time_in_office <= 3)%>style = "background: red;" <% end  %> ><%= r3.time_in_office if r3.present? %></td>
              <td><%= date_report %></td>
              <td>
                <%
                  diff = nil
                  if r1.present? && r1.time_in_office != 0
                    if r2.present? && r2.time_in_office - r1.time_in_office <= -2 && r2.time_in_office != 0
                      diff = r2.time_in_office - r1.time_in_office
                    else
                      if r3.present?
                        if (r3.time_in_office.round(1) - r1.time_in_office) <= -2 && r3.time_in_office != 0
                          diff = r3.time_in_office.round(1) - r1.time_in_office
                        end
                      end
                    end
                  else
                    if r3.present? && r2.present?
                      if (r2.time_in_office.round(1) - r3.time_in_office) <= -3 && r2.time_in_office != 0
                        diff = r2.time_in_office.round(1) - r3.time_in_office
                      end
                    end
                  end
                %>
                <% if diff.present? %>
                  <button class="btn btn-danger btn-sm" ><%= diff.round(1) if diff.present? %></button>
                <% else %>
                -
                <% end %>
              </td>
                </tr>
            <% end %>
          <% end %>


          </tbody>
        </table>
      </div>

    </div>

    <hr>

  </div> <!-- /container -->

</main>

<footer class="container">
  <p>&copy; <a href="https://www.intagleo.com/" target="_blank">Intagleo.com</a> 2019</p>
</footer>
<script type="text/javascript">
    $(document).ready(function(){
        $('#page-loader').hide();

        $('.datepicker').datepicker();
    });
    // $( "#generate_report_btn" ).click(function() {
    //     $.ajax({
    //      url: "/reports/generate_sheet",
    //      type: "GET",
    //      success: function(data) {
          
    //       alert(data.filename);
    //       // $.ajax({url: "/reports/download_sheet", type: "GET"});
            
            
    //        }
    //      });
    //     // $('#page-loader').show();
    // });
    function openPopup(link)
      {
          // link.hide();
          
      
          var myWindow = window.open(link.href,'');

          // return false;
      }
    $( "#generate_report" ).click(function(e) {
      e.preventDefault();
        // alert("Your downloading will begin shortly");
        // $('#page-loader').show();
    });
    $( "#search_button" ).click(function() {
        $('#page-loader').show();
    if ($('#start_date').val() == "" && $('#end_date').val() == "" && $('#search_name').val() == "")
    {
        alert("Please enter name or date");
        $('#page-loader').hide();
        return false;
    }
    if (($('#end_date').val() == "" || $('#start_date').val() == "") && $('#search_name').val() == "")
    {
        if ($('#end_date').val() == "")
        {
            alert("Please enter end date");
            $('#page-loader').hide();
            return false;
        }
        if ($('#start_date').val() == "")
        {
            alert("Please enter start date");
            $('#page-loader').hide();
            return false;
        }
    }
    });
</script>